import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ShopByCategory from "../components/ShopByCategory";
import TopProducts from "../containers/TopProducts";
import BackToTop from "../components/BackToTop";
import { Product_Api } from "../Utils/Api";
import styled from "styled-components";
import Sidebar from "../components/sidebar/Sidebar";
import HomeContent from "../components/HomeContent";

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NestMart | Next 12</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" common_width section_padding">
        <TopContainer>
          <Sidebar />
          <HomeContent data={data} />
        </TopContainer>
        <ShopByCategory />
        <TopProducts data={data} />
        <BackToTop />
      </div>
    </div>
  );
};

export default Home;

const TopContainer = styled.div`
  display: flex;
  gap: 20px;
`;


export async function getServerSideProps() {
  // let res = await fetch(Product_Api + "/products");
  let res = await fetch(Product_Api + "/products");
  let data = await res.json();

  return { props: { data } };
}
